---
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: sdr-adsb
spec:
  discoveryHandler:
    discoveryDetails: |
      groupRecursive: true
      udevRules:
      - ATTR{idVendor}=="0bda", ATTR{idProduct}=="2832", ATTR{serial}=="109000"
      - ATTR{idVendor}=="0bda", ATTR{idProduct}=="2838", ATTR{serial}=="109000"
    name: udev
  brokerProperties: {}
  capacity: 1
