---
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: yubikey-white
spec:
  discoveryHandler:
    discoveryDetails: |
      groupRecursive: true
      udevRules: 
      - ATTR{idVendor}=="1050", ATTR{idProduct}=="0407", ATTR{serial}=="0016833810"
    name: udev
  brokerProperties: {}
  capacity: 1
