apiVersion: v1
kind: Service
metadata:
  name: {{ include "adsb.fullname" . }}-http
  labels:
    app.kubernetes.io/component: http
    {{- include "adsb.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/component: ultrafeeder
    {{- include "adsb.selectorLabels" . | nindent 4 }}