apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adsb.fullname" . }}
  labels:
    app.kubernetes.io/component: ""
    {{- include "adsb.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: local-path
