{{- $vaultName := .Values.azureKeyVaultSecret.vaultName | required ".Values.azureKeyVaultSecret.vaultName is required." -}}
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ include "folder2k8s.fullname" . }}-client-id
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "folder2k8s.labels" . | nindent 4 }}
spec:
  vault:
    name: {{ $vaultName }}
    object:
      name: {{ .Values.azureKeyVaultSecret.clientIdSecretName }}
      type: secret
  output: 
    secret: 
      name: {{ include "folder2k8s.fullname" . }}
      dataKey: client-id
