{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "folder2k8s.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "folder2k8s.labels" . | nindent 4 }}
{{- end }}
