apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "folder2k8s.fullname" . }}
  labels:
    {{- include "folder2k8s.labels" . | nindent 4 }}
rules:
- apiGroups:
  - helm.cattle.io
  resources:
  - helmcharts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
