ref: master

azureKeyVaultSecret:
  vaultName:
  clientIdSecretName: github-app-client-id
  installationIdSecretName: github-app-installation-id
  privateKeySecretName: github-app-private-key

image:
  repository: ghcr.io/illallangi/folder2k8s
  pullPolicy: IfNotPresent
  tag: v0.1.0

git_sync:
  image:
    repository: registry.k8s.io/git-sync/git-sync
    pullPolicy: IfNotPresent
    tag: v4.3.0

serviceAccount:
  create: true
  name: ""
