apiVersion: v1
kind: Service
metadata:
  name: {{ include "adsb.fullname" . }}-basestation
  labels:
    app.kubernetes.io/component: basestation
    {{- include "adsb.labels" . | nindent 4 }}
spec:
  ports:
  - name: basestation
    port: 30003
    targetPort: basestation
  selector:
    app.kubernetes.io/component: ultrafeeder
    {{- include "adsb.selectorLabels" . | nindent 4 }}