apiVersion: v1
kind: Service
metadata:
  name: {{ include "adsb.fullname" . }}-beast
  labels:
    app.kubernetes.io/component: beast
    {{- include "adsb.labels" . | nindent 4 }}
spec:
  ports:
  - name: beast
    port: 30005
    targetPort: beast
  selector:
    app.kubernetes.io/component: ultrafeeder
    {{- include "adsb.selectorLabels" . | nindent 4 }}